# Generated by Django 3.2.9 on 2022-02-02 17:44

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='staticfiles/images')),
                ('price', models.DecimalField(decimal_places=2, default=10.0, max_digits=6)),
                ('description', models.TextField(max_length=200)),
                ('note', models.TextField(default='', max_length=200)),
                ('ingredients', models.TextField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=api.models.generate_unique_code)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('ordered', models.ManyToManyField(to='api.Food')),
            ],
        ),
    ]
