# Generated by Django 3.2.9 on 2021-11-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_size', models.CharField(max_length=2)),
                ('background_color', models.CharField(max_length=50)),
                ('text_color', models.CharField(max_length=50)),
                ('button_color', models.CharField(max_length=50)),
                ('button_text_color', models.CharField(max_length=50)),
                ('button_position', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
