# Generated by Django 3.2.9 on 2022-02-15 16:54

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodquantity',
            name='code',
            field=models.IntegerField(default=api.models.generate_unique_code),
        ),
    ]
