# Generated by Django 3.2.9 on 2021-11-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='button_position_2',
            field=models.CharField(default=10, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='height',
            field=models.CharField(default=10, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='left',
            field=models.CharField(default=10, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='width',
            field=models.CharField(default=10, max_length=50),
            preserve_default=False,
        ),
    ]
