# Generated by Django 3.2.9 on 2022-02-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_foodquantity_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodquantity',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
