# Generated by Django 3.2.9 on 2022-02-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_foodquantity_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('Burgery', 'Burgery'), ('Przystawki', 'Przystawki'), ('Podrasuj Burger', 'Podrasuj Burger'), ('Sałatki', 'Sałatki'), ('Dla Dzieci', 'Dla Dzieci')], default='Burgery', max_length=50),
        ),
    ]
