# Generated by Django 3.2.9 on 2022-02-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_food_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
