# Generated by Django 3.2.9 on 2022-02-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_order_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payed',
            field=models.BooleanField(default=True),
        ),
    ]
