# Generated by Django 3.2.9 on 2022-05-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220519_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='dodatkowe_mieso',
        ),
        migrations.AddField(
            model_name='foodquantity',
            name='dodatkowe_mieso',
            field=models.BooleanField(default=False),
        ),
    ]
