# Generated by Django 3.2.9 on 2022-05-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20220520_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dodatkowe_mieso',
            field=models.BooleanField(default=False),
        ),
    ]
