# Generated by Django 3.2.9 on 2022-05-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_order_dodatkowe_mieso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dodatkowe_mieso',
        ),
        migrations.AddField(
            model_name='food',
            name='dodatkowe_mieso',
            field=models.BooleanField(default=False),
        ),
    ]
