# Generated by Django 3.2.9 on 2022-05-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20220520_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodquantity',
            name='bataty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodquantity',
            name='frytki',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodquantity',
            name='krazki',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodquantity',
            name='kulki',
            field=models.BooleanField(default=False),
        ),
    ]
